export const index = {
  components: {
    Button: 'Button',
    Input: 'Input',
    Select: 'Select',
    Textarea: 'Textarea',
    Label: 'Label',
    Badge: 'Badge',
    Card: 'Card',
    CardHeader: 'CardHeader',
    CardBody: 'CardBody',
    Tabs: 'Tabs',
    Modal: 'Modal',
    Tooltip: 'Tooltip',
  },
  hooks: {
    useLeads: 'useLeads',
    useSetterActivities: 'useSetterActivities',
    useRevenueGoals: 'useRevenueGoals',
    useDashboardData: 'useDashboardData',
    useProjectionData: 'useProjectionData',
    useFilterOptions: 'useFilterOptions',
    useProjectionAssumptions: 'useProjectionAssumptions',
    useDashboardFilters: 'useDashboardFilters',
    useUIStore: 'useUIStore',
  },
  lib: {
    supabase: 'supabase',
    queryClient: 'queryClient',
    computations: 'computations',
    constants: 'constants',
    utils: 'utils',
  },
  types: 'types',
};